//pages
export QuestionAdd from './QuestionAdd/index.js'
export AdminPanel from './AdminPanel/'
export AdminProfile from './AdminProfile/'
export ApplyCompleted from './ApplyCompleted/'
export ApplyForm from './ApplyForm/'
export InterView from './InterView/'
export Login from './Login/'
export NewQuestionSet from './NewQuestionSet/'
export QuestionList from './QuestionList/'
export QuestionSetDetails from './QuestionSetDetails/'
export SignUp from './SignUp/'
export TestCompleted from './TestCompleted/'
export UserProfile from './UserProfile/'
export ViewQuestion from './ViewQuestion/'
export SkillTest from './SkillTest'
export ListOfParticipants from './ParticipantList'
export Deneme from './Deneme/deneme'
