version: "2"

services:

  frontend:
    image: dist.fikrimuhal.com/animatedpotato/frontend
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '80:8081'
#    external_links:
#      - bogazici
    networks:
      - animatedpotato
    hostname: frontend

networks:
  animatedpotato:
    external:
        name: animatedpotato